// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package main

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDecodeNote(in *jlexer.Lexer, out *Note) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "content":
			out.Content = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func easyjsonEncodeNote(out *jwriter.Writer, in Note) {
	out.RawByte('{')
	{
		const prefix string = "\"id\":"
		out.RawString(prefix)
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

func (v Note) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodeNote(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v Note) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodeNote(w, v)
}

func (v *Note) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDecodeNote(&r, v)
	return r.Error()
}

func (v *Note) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDecodeNote(l, v)
}

func easyjsonDecodeNoteList(in *jlexer.Lexer, out *NoteList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		*out = nil
		return
	}
	in.Delim('[')
	if *out == nil {
		if !in.IsDelim(']') {
			*out = make(NoteList, 0, 4)
		} else {
			*out = NoteList{}
		}
	} else {
		*out = (*out)[:0]
	}
	for !in.IsDelim(']') {
		var v1 Note
		easyjsonDecodeNote(in, &v1)
		*out = append(*out, v1)
		in.WantComma()
	}
	in.Delim(']')
	if isTopLevel {
		in.Consumed()
	}
}

func easyjsonEncodeNoteList(out *jwriter.Writer, in NoteList) {
	if in == nil {
		out.RawString("null")
		return
	}
	out.RawByte('[')
	for i := range in {
		if i > 0 {
			out.RawByte(',')
		}
		easyjsonEncodeNote(out, in[i])
	}
	out.RawByte(']')
}

func (v NoteList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodeNoteList(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v NoteList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodeNoteList(w, v)
}

func (v *NoteList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDecodeNoteList(&r, v)
	return r.Error()
}

func (v *NoteList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDecodeNoteList(l, v)
}